workflows:
  rust_pipeline_macos:
    name: Rust CI/CD Pipeline for macOS
    triggering:
      events:
        - push
        - pull_request
    environment:
      vars:
        RUST_VERSION: "stable"
    scripts:
      - name: Install Rustup and Rust
        script: |
          set -e
          echo "Installing Rust on macOS..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup install $RUST_VERSION || { echo "Failed to install Rust"; exit 1; }
      - name: Verify Rust Installation
        script: |
          echo "Verifying Rust installation..."
          export PATH="$HOME/.cargo/bin:$PATH"
          rustc --version || { echo "Rust compiler is not installed"; exit 1; }
          cargo --version || { echo "Cargo is not installed"; exit 1; }
      - name: Build Project
        script: |
          set -e
          echo "Building the project on macOS..."
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo build --release || { echo "Cargo build failed on macOS"; exit 1; }
      - name: Test Project
        script: |
          set -e
          echo "Running tests on macOS..."
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo test --release || { echo "Cargo tests failed on macOS"; exit 1; }
      - name: Debug Build Output
        script: |
          echo "Listing target/release directory contents..."
          export PATH="$HOME/.cargo/bin:$PATH"
          ls -la target/release || { echo "Failed to list target/release contents"; exit 1; }
    artifacts:
      - target/release/*.dylib
